<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Gravicode.Science.Benchmarks.GraviText</RootNamespace>
    <AssemblyName>GraviText.Benchmark</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <ProjectReference Include="..\..\src\GraviText\GraviText.csproj" />
  </ItemGroup>

</Project>