"""
Generates src/MediaPipeNet.Inference/Models/ModelCatalog.Quantized.g.cs from
models/onnx/quantized/manifest.json (written by quantize_models.py).

    python tools/model-conversion/generate_quantized_catalog.py
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "models" / "onnx" / "quantized" / "manifest.json"
OUT = ROOT / "src" / "MediaPipeNet.Inference" / "Models" / "ModelCatalog.Quantized.g.cs"
PRECISION = {"fp16": "ModelPrecision.Float16", "int8": "ModelPrecision.Int8"}


def main() -> None:
    entries = json.loads(MANIFEST.read_text())
    rows = "\n".join(
        f'            Variant("{e["id"]}", {PRECISION[e["precision"]]}, "{e["file"]}", "{e["sha256"]}", {e["bytes"]:_}),'
        for e in entries)
    OUT.write_text(f"""// <auto-generated>
// Generated by tools/model-conversion/generate_quantized_catalog.py from models/onnx/quantized/manifest.json.
// Do not edit by hand.
// </auto-generated>

#nullable enable

namespace MediaPipeNet.Inference.Models;

public static partial class ModelCatalog
{{
    /// <summary>NuGet package holding the reduced-precision (FP16 / INT8) model variants.</summary>
    public const string QuantizedPackage = "Gravicode.MediaPipeNet.Models.Quantized";

    private static readonly Lazy<Dictionary<(string Id, ModelPrecision Precision), ModelDescriptor>> s_variants = new(() =>
    {{
        ModelDescriptor[] variants =
        [
{rows}
        ];
        return variants.ToDictionary(v => (v.Id[..v.Id.LastIndexOf('.')], v.Precision));
    }});

    /// <summary>Every reduced-precision variant, each validated against its float32 model (cosine ≥ 0.999 for FP16, ≥ 0.99 for INT8).</summary>
    public static IReadOnlyList<ModelDescriptor> QuantizedVariants => [.. s_variants.Value.Values];

    /// <summary>
    /// The <paramref name="precision"/> variant of <paramref name="model"/>, or null when the model has none
    /// (or <paramref name="precision"/> is <see cref="ModelPrecision.Float32"/>).
    /// </summary>
    public static ModelDescriptor? GetVariant(ModelDescriptor model, ModelPrecision precision)
    {{
        ArgumentNullException.ThrowIfNull(model);
        if (precision == ModelPrecision.Float32 || model.Precision != ModelPrecision.Float32) return null;
        return s_variants.Value.GetValueOrDefault((model.Id, precision));
    }}

    private static ModelDescriptor Variant(string id, ModelPrecision precision, string fileName, string sha256, long size)
    {{
        var model = Find(id) ?? throw new InvalidOperationException($"Unknown model {{id}}.");
        string suffix = precision == ModelPrecision.Float16 ? "fp16" : "int8";
        return model with
        {{
            Id = $"{{id}}.{{suffix}}",
            FileName = fileName,
            Sha256 = sha256,
            SizeBytes = size,
            PackageId = QuantizedPackage,
            Title = $"{{model.Title}} ({{suffix.ToUpperInvariant()}})",
            Precision = precision,
        }};
    }}
}}
""", encoding="utf-8")
    print(f"wrote {OUT} ({len(entries)} variants)")


if __name__ == "__main__":
    main()
