<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Gravicode.Science.Tests.GraviGraph</RootNamespace>
    <AssemblyName>GraviGraph.Tests</AssemblyName>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\src\GraviGraph\GraviGraph.csproj" />
  </ItemGroup>

</Project>