"""Writes UnicodeTables.g.cs from Python's unicodedata. Run from this folder: python make_tables.py

The tables are what Unicode normalization needs and .NET cannot supply under InvariantGlobalization,
where String.Normalize returns its input unchanged:

  decompositions   code point -> its decomposition, canonical or compatibility (the latter flagged)
  combining        code point -> canonical combining class, for every non-zero class
  compositions     (first, second) -> the primary composite, for every canonical pair NFC recomposes

Hangul syllables are algorithmic and handled in code.
"""
import sys
import unicodedata

decompositions = []
combining = []
compositions = []

for code in range(0x110000):
    if 0xD800 <= code <= 0xDFFF or 0xAC00 <= code <= 0xD7A3:
        continue
    ch = chr(code)
    ccc = unicodedata.combining(ch)
    if ccc:
        combining.append((code, ccc))

    raw = unicodedata.decomposition(ch)
    if not raw:
        continue
    compat = raw.startswith("<")
    parts = raw.split()
    if compat:
        parts = parts[1:]
    mapping = [int(p, 16) for p in parts]
    decompositions.append((code, compat, mapping))

    # A canonical pair is a composition when NFC of the pair gives back this code point - which
    # leaves out the composition exclusions and singletons.
    if not compat and len(mapping) == 2:
        if unicodedata.normalize("NFC", chr(mapping[0]) + chr(mapping[1])) == ch:
            compositions.append((mapping[0], mapping[1], code))


def chunks(text, width=110):
    return [text[i:i + width] for i in range(0, len(text), width)]


decomp_text = ";".join(
    f"{c:X}{'!' if compat else ':'}{' '.join(f'{m:X}' for m in mapping)}" for c, compat, mapping in decompositions)
comb_text = ";".join(f"{c:X}:{k}" for c, k in combining)
comp_text = ";".join(f"{a:X} {b:X}:{c:X}" for a, b, c in compositions)


def literal(name, text):
    lines = chunks(text)
    body = "\n".join(f'        "{line}" +' for line in lines)
    return f"    internal const string {name} =\n{body}\n        \"\";\n"


with open("UnicodeTables.g.cs", "w", encoding="utf-8", newline="\n") as out:
    out.write("// <auto-generated>\n")
    out.write(f"// Generated by make_tables.py from Python {sys.version.split()[0]}'s unicodedata, "
              f"Unicode {unicodedata.unidata_version}. Do not edit.\n")
    out.write("// </auto-generated>\n\n")
    out.write("namespace Gravicode.HFNet.GraviTokenizers.Unicode;\n\n")
    out.write("internal static class UnicodeTables\n{\n")
    out.write(f"    internal const string Version = \"{unicodedata.unidata_version}\";\n\n")
    out.write("    /// <summary>code:mapping (canonical) or code!mapping (compatibility), hex, ';'-separated.</summary>\n")
    out.write(literal("Decompositions", decomp_text))
    out.write("\n    /// <summary>code:class for every non-zero canonical combining class.</summary>\n")
    out.write(literal("CombiningClasses", comb_text))
    out.write("\n    /// <summary>first second:composite for every canonical composition.</summary>\n")
    out.write(literal("Compositions", comp_text))
    out.write("}\n")

print(len(decompositions), "decompositions,", len(combining), "combining classes,", len(compositions),
      "compositions, Unicode", unicodedata.unidata_version)
