// <auto-generated>
// Generated by tools/model-conversion/generate_quantized_catalog.py from models/onnx/quantized/manifest.json.
// Do not edit by hand.
// </auto-generated>

#nullable enable

namespace MediaPipeNet.Inference.Models;

public static partial class ModelCatalog
{
    /// <summary>NuGet package holding the reduced-precision (FP16 / INT8) model variants.</summary>
    public const string QuantizedPackage = "Gravicode.MediaPipeNet.Models.Quantized";

    private static readonly Lazy<Dictionary<(string Id, ModelPrecision Precision), ModelDescriptor>> s_variants = new(() =>
    {
        ModelDescriptor[] variants =
        [
            Variant("deeplab_v3", ModelPrecision.Float16, "deeplab_v3.fp16.onnx", "c0d7df972ff9cc558b59690733eec1b1d65259983ca797cf67ea71889d5a8e63", 1_414_147),
            Variant("deeplab_v3", ModelPrecision.Int8, "deeplab_v3.int8.onnx", "0920fcc32152781376b76d1e53a0462fa17b1f5c44e6b60dde0f6e7b998178e5", 818_362),
            Variant("efficientdet_lite0", ModelPrecision.Float16, "efficientdet_lite0.fp16.onnx", "11ac56a3cc9b88e76c11a77c36315b9921ff1cb66baebf3099544d9509206c19", 6_876_265),
            Variant("efficientdet_lite0", ModelPrecision.Int8, "efficientdet_lite0.int8.onnx", "6d023f809ecdac0a79f260aec9d0e9bf070786583f2bcdcc164f87820c2a5681", 3_790_461),
            Variant("efficientnet_lite0", ModelPrecision.Float16, "efficientnet_lite0.fp16.onnx", "0a9c591e27f638b2bdd60d0210db3fd35a262b40dc5bd22ee85f326a6e3658ca", 9_354_846),
            Variant("face_detection_full_range", ModelPrecision.Float16, "face_detection_full_range.fp16.onnx", "9c7881822e9cd10940caeb1ad21380be4913a39d09831c18efaeb49990f481f2", 1_062_420),
            Variant("face_detection_full_range", ModelPrecision.Int8, "face_detection_full_range.int8.onnx", "0b8aac5b710ed02517d7d447a265e7aa9ba7a642f78fa40ab18b82a9e59fd668", 659_002),
            Variant("face_landmarks_detector", ModelPrecision.Float16, "face_landmarks_detector.fp16.onnx", "cac51b2ad49bfe1fdb250ebaf1b9e9ee191c604bafbda3dfabe668db068a459b", 2_560_504),
            Variant("face_landmarks_detector", ModelPrecision.Int8, "face_landmarks_detector.int8.onnx", "77629b811eab206200c27b3d5d4a9216de8228244ac9b9989dbef6482fd41d70", 1_460_160),
            Variant("hand_landmarks_detector", ModelPrecision.Float16, "hand_landmarks_detector.fp16.onnx", "ea701b727fb76963aac5a5823174d064f6ffac7a267ec7e12cb56197d029d582", 5_484_495),
            Variant("language_detector", ModelPrecision.Float16, "language_detector.fp16.onnx", "acce2099975b996ebaa7d87fed7c75ac6cc98d28c7b5a6b117ecceb768d377ff", 1_918_195),
            Variant("magic_touch", ModelPrecision.Float16, "magic_touch.fp16.onnx", "06393a321169f5f4e4a01d2e893a52ce664ebe664debd6bc2a5ff94ead58880a", 6_234_557),
            Variant("mobilenet_v3_small_embedder", ModelPrecision.Float16, "mobilenet_v3_small_embedder.fp16.onnx", "ed6687a9fd531597f39f175e30786e0ca32c91dc09077988543cfb23554e8971", 2_207_713),
            Variant("mobilenet_v3_small_embedder", ModelPrecision.Int8, "mobilenet_v3_small_embedder.int8.onnx", "799d54c481ecfe2bcaa493c2336714424d98ea366194c3934add06030ace8318", 1_236_027),
            Variant("palm_detection", ModelPrecision.Float16, "palm_detection.fp16.onnx", "e7f4b71fb7285854b36bb11227941898c228a3e934d9b5fdc699353a6c9fa284", 2_342_680),
            Variant("palm_detection", ModelPrecision.Int8, "palm_detection.int8.onnx", "ae37df4ce655e9e1b5b3d29aa4db94950f4b43172e15ff6ca829833c9358def4", 1_294_504),
            Variant("pose_detection", ModelPrecision.Float16, "pose_detection.fp16.onnx", "23c49564a9a2a9af0a262812700e1cf125be0a8fc03129d3fec66183b91a6e6b", 6_016_365),
            Variant("pose_detection", ModelPrecision.Int8, "pose_detection.int8.onnx", "89aa53d70471f87c027d12b1f31d1bc39582cd8f3415d83b2278b690895e7a9b", 3_237_301),
            Variant("pose_landmarks_detector_full", ModelPrecision.Float16, "pose_landmarks_detector_full.fp16.onnx", "253e67ad05236fba2740a9658337ba79080380ef53ac5e5cd8e5acef6910f79f", 6_455_641),
            Variant("pose_landmarks_detector_lite", ModelPrecision.Float16, "pose_landmarks_detector_lite.fp16.onnx", "4c09e210aee7cf1409490a9ddef4507920960f26b5e2b29b431a5ddffabb8223", 2_835_170),
            Variant("selfie_multiclass", ModelPrecision.Float16, "selfie_multiclass.fp16.onnx", "60d1087702fe0080ea736ce77cfa789e6508fd0e373256a5c4d8360bab59df83", 8_371_528),
            Variant("selfie_multiclass", ModelPrecision.Int8, "selfie_multiclass.int8.onnx", "7f4423272d7783677eccff62ca35bf47d75acf20b7031211307f907221b1d39a", 4_418_975),
        ];
        return variants.ToDictionary(v => (v.Id[..v.Id.LastIndexOf('.')], v.Precision));
    });

    /// <summary>Every reduced-precision variant, each validated against its float32 model (cosine ≥ 0.999 for FP16, ≥ 0.99 for INT8).</summary>
    public static IReadOnlyList<ModelDescriptor> QuantizedVariants => [.. s_variants.Value.Values];

    /// <summary>
    /// The <paramref name="precision"/> variant of <paramref name="model"/>, or null when the model has none
    /// (or <paramref name="precision"/> is <see cref="ModelPrecision.Float32"/>).
    /// </summary>
    public static ModelDescriptor? GetVariant(ModelDescriptor model, ModelPrecision precision)
    {
        ArgumentNullException.ThrowIfNull(model);
        if (precision == ModelPrecision.Float32 || model.Precision != ModelPrecision.Float32) return null;
        return s_variants.Value.GetValueOrDefault((model.Id, precision));
    }

    private static ModelDescriptor Variant(string id, ModelPrecision precision, string fileName, string sha256, long size)
    {
        var model = Find(id) ?? throw new InvalidOperationException($"Unknown model {id}.");
        string suffix = precision == ModelPrecision.Float16 ? "fp16" : "int8";
        return model with
        {
            Id = $"{id}.{suffix}",
            FileName = fileName,
            Sha256 = sha256,
            SizeBytes = size,
            PackageId = QuantizedPackage,
            Title = $"{model.Title} ({suffix.ToUpperInvariant()})",
            Precision = precision,
        };
    }
}
