<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Gravicode.HFNet.Samples.GraviTransformers</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\GraviTransformers\GraviTransformers.csproj" />
  </ItemGroup>
</Project>
