<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1303;CA2007;CA1822;CA2000;CA1515;CA1307;CA1852;CA1812;CA1861;CA1310;CA5394;CA1869;CA1826</NoWarn>
  </PropertyGroup>
</Project>
