using MediaPipeNet.Tasks.Vision;

namespace MediaPipeNet.Tasks.Tests;

/// <summary>
/// Cross-validation against the official Google MediaPipe Python package (tests/assets/golden,
/// generated by tools/golden/generate_golden.py). Tolerances reflect resampling differences between
/// OpenCV and MediaPipe.NET's image-to-tensor conversion.
/// </summary>
public class GoldenTests
{
    [Fact]
    public void Face_detector_matches_mediapipe()
    {
        using var detector = FaceDetector.Create(new() { BaseOptions = Fixtures.Base });
        using var image = Fixtures.Load("portrait.jpg");
        var result = detector.Detect(image);
        var expected = Golden.For("face_detector", "portrait.jpg")[0];
        result.Detections.Should().ContainSingle();
        var face = result.Detections[0];
        RectF.IntersectionOverUnion(face.BoundingBox, Golden.Box(expected)).Should().BeGreaterThan(0.9f);
        face.Score.Should().BeApproximately(expected.GetProperty("categories")[0].GetProperty("score").GetSingle(), 0.03f);
        face.Keypoints.Should().HaveCount(6);
        var kp = expected.GetProperty("keypoints");
        for (int i = 0; i < 6; i++)
        {
            face.Keypoints[i].X.Should().BeApproximately(kp[i].GetProperty("x").GetSingle(), 0.012f);
            face.Keypoints[i].Y.Should().BeApproximately(kp[i].GetProperty("y").GetSingle(), 0.012f);
        }
    }

    [Fact]
    public void Face_landmarker_matches_mediapipe()
    {
        using var landmarker = FaceLandmarker.Create(new() { BaseOptions = Fixtures.Base, OutputFaceBlendshapes = true });
        using var image = Fixtures.Load("portrait.jpg");
        var result = landmarker.Detect(image);
        var expected = Golden.For("face_landmarker", "portrait.jpg");
        result.Faces.Should().ContainSingle();
        var face = result.Faces[0];
        face.Landmarks.Should().HaveCount(478);
        Golden.MeanError(face.Landmarks, Golden.Landmarks(expected.GetProperty("landmarks")[0])).Should().BeLessThan(0.006f);
        var expectedBlend = expected.GetProperty("blendshapes")[0].EnumerateArray().ToDictionary(e => e.GetProperty("name").GetString()!, e => e.GetProperty("score").GetSingle());
        face.Blendshapes.Should().HaveCount(52);
        foreach (var name in new[] { "mouthSmileLeft", "mouthSmileRight", "jawOpen", "eyeBlinkLeft" })
            face.GetBlendshape(name).Should().BeApproximately(expectedBlend[name], 0.08f, name);
    }

    [Theory]
    [InlineData("thumb_up.jpg", 0.02f)]
    [InlineData("victory.jpg", 0.01f)]
    [InlineData("pointing_up.jpg", 0.01f)]
    public void Hand_landmarker_matches_mediapipe(string imageName, float tolerance)
    {
        using var landmarker = HandLandmarker.Create(new() { BaseOptions = Fixtures.Base });
        using var image = Fixtures.Load(imageName);
        var result = landmarker.Detect(image);
        var expected = Golden.For("hand_landmarker", imageName);
        result.Hands.Should().ContainSingle();
        var hand = result.Hands[0];
        Golden.MeanError(hand.Landmarks, Golden.Landmarks(expected.GetProperty("landmarks")[0])).Should().BeLessThan(tolerance);
        hand.Handedness.CategoryName.Should().Be(expected.GetProperty("handedness")[0][0].GetProperty("name").GetString());
        hand.WorldLandmarks.Should().HaveCount(21);
        hand.PresenceScore.Should().BeGreaterThan(0.9f);
        hand[HandLandmark.Wrist].Should().Be(hand.Landmarks[0]);
    }

    [Theory]
    [InlineData("thumb_up.jpg")]
    [InlineData("victory.jpg")]
    [InlineData("pointing_up.jpg")]
    public void Gesture_recognizer_matches_mediapipe(string imageName)
    {
        using var recognizer = GestureRecognizer.Create(new() { BaseOptions = Fixtures.Base });
        using var image = Fixtures.Load(imageName);
        var result = recognizer.Recognize(image);
        var expected = Golden.For("gesture_recognizer", imageName).GetProperty("gestures")[0][0];
        result.Hands.Should().ContainSingle();
        result.Hands[0].TopGesture.CategoryName.Should().Be(expected.GetProperty("name").GetString());
        result.Hands[0].TopGesture.Score.Should().BeApproximately(expected.GetProperty("score").GetSingle(), 0.15f);
    }

    [Fact]
    public void Pose_landmarker_matches_mediapipe()
    {
        using var landmarker = PoseLandmarker.Create(new() { BaseOptions = Fixtures.Base, OutputSegmentationMasks = true });
        using var image = Fixtures.Load("pose.jpg");
        var result = landmarker.Detect(image);
        result.Poses.Should().ContainSingle();
        var pose = result.Poses[0];
        var expected = Golden.For("pose_landmarker", "pose.jpg").GetProperty("landmarks")[0];
        Golden.MeanError(pose.Landmarks, Golden.Landmarks(expected)).Should().BeLessThan(0.012f);
        pose[PoseLandmark.Nose].Visibility.Should().BeGreaterThan(0.9f);
        pose.WorldLandmarks.Should().HaveCount(33);
        pose.SegmentationMask!.Coverage().Should().BeInRange(0.03f, 0.2f);
    }

    [Fact]
    public void Selfie_segmenter_matches_mediapipe()
    {
        using var segmenter = ImageSegmenter.Create(new() { BaseOptions = Fixtures.Base });
        using var image = Fixtures.Load("portrait.jpg");
        var mask = segmenter.Segment(image).ConfidenceMask;
        var expected = Golden.For("selfie_segmenter", "portrait.jpg");
        mask.Width.Should().Be(expected.GetProperty("width").GetInt32());
        mask.Height.Should().Be(expected.GetProperty("height").GetInt32());
        mask.Data.Average().Should().BeApproximately(expected.GetProperty("mean").GetSingle(), 0.01f);
        mask.Coverage().Should().BeApproximately(expected.GetProperty("foreground_fraction").GetSingle(), 0.01f);
    }

    [Fact]
    public void Object_detector_matches_mediapipe()
    {
        using var detector = ObjectDetector.Create(new() { BaseOptions = Fixtures.Base });
        using var image = Fixtures.Load("cats_and_dogs.jpg");
        var result = detector.Detect(image);
        var expected = Golden.For("object_detector", "cats_and_dogs.jpg").EnumerateArray().ToArray();
        result.Detections.Should().HaveCount(expected.Length);
        foreach (var e in expected)
        {
            var label = e.GetProperty("categories")[0].GetProperty("name").GetString();
            var box = Golden.Box(e);
            result.Detections.Should().Contain(d => d.TopCategory.CategoryName == label && RectF.IntersectionOverUnion(d.BoundingBox, box) > 0.85f,
                $"a {label} near {box}");
        }
    }

    [Fact]
    public void Image_classifier_matches_mediapipe()
    {
        using var classifier = ImageClassifier.Create(new() { BaseOptions = Fixtures.Base });
        using var image = Fixtures.Load("burger.jpg");
        var result = classifier.Classify(image);
        var expected = Golden.For("image_classifier", "burger.jpg")[0];
        result.Categories.Should().HaveCount(5);
        result.Categories[0].CategoryName.Should().Be(expected.GetProperty("name").GetString());
        result.Categories[0].Index.Should().Be(expected.GetProperty("index").GetInt32());
        result.Categories[0].Score.Should().BeApproximately(expected.GetProperty("score").GetSingle(), 0.08f);
    }
}
