using MediaPipeNet.Tasks.Vision;
using MediaPipeNet.Tasks.Vision.Processing;

namespace MediaPipeNet.Tasks.Tests;

/// <summary>
/// Cross-validation of the 0.2 / 0.3 features against the official MediaPipe Python package
/// (tests/assets/golden/mediapipe_python_reference_v2.json, generated by tools/golden/generate_golden_v2.py).
/// </summary>
public class GoldenV2Tests
{
    // The face in pose.jpg is ~50 px wide (~10 px in the 192×192 tensor): neighbouring anchors (4 px apart)
    // score almost equally, so resampling differences between OpenCV and MediaPipe.NET shift the weighted
    // NMS result by up to one anchor cell (verified with the ONNX model and OpenCV preprocessing in Python).
    [Theory]
    [InlineData("pose.jpg", 0.45f, 0.025f)]
    [InlineData("portrait.jpg", 0.85f, 0.01f)]
    public void Full_range_face_detector_matches_mediapipe(string imageName, float minIou, float keypointTolerance)
    {
        using var detector = FaceDetector.Create(new() { BaseOptions = Fixtures.Base, Model = FaceDetectorModel.FullRange });
        using var image = Fixtures.Load(imageName);
        var result = detector.Detect(image);
        var expected = Golden.V2("face_detector_full_range").GetProperty(imageName)[0];
        result.Detections.Should().ContainSingle();
        var face = result.Detections[0];
        RectF.IntersectionOverUnion(face.BoundingBox, Golden.Box(expected)).Should().BeGreaterThan(minIou);
        face.Score.Should().BeApproximately(expected.GetProperty("score").GetSingle(), 0.05f);
        var kp = expected.GetProperty("keypoints");
        for (int i = 0; i < 6; i++)
        {
            face.Keypoints[i].X.Should().BeApproximately(kp[i].GetProperty("x").GetSingle(), keypointTolerance);
            face.Keypoints[i].Y.Should().BeApproximately(kp[i].GetProperty("y").GetSingle(), keypointTolerance);
        }
    }

    [Fact]
    public void Facial_transformation_matrix_matches_mediapipe()
    {
        using var landmarker = FaceLandmarker.Create(new() { BaseOptions = Fixtures.Base, OutputFacialTransformationMatrixes = true });
        using var image = Fixtures.Load("portrait.jpg");
        var face = landmarker.Detect(image).Faces.Should().ContainSingle().Subject;
        var m = face.FacialTransformationMatrix!;
        m.Should().HaveCount(16);
        var expected = Golden.V2("face_transformation_matrix").GetProperty("portrait.jpg");
        for (int r = 0; r < 4; r++)
        {
            for (int c = 0; c < 4; c++)
            {
                float e = expected[r][c].GetSingle();
                // Rotation within ~2°, translation within ~1.5 cm (landmarks differ slightly from MediaPipe's).
                m[r * 4 + c].Should().BeApproximately(e, c == 3 ? 1.5f : 0.04f, $"M[{r},{c}]");
            }
        }
        var numerics = face.GetTransformMatrix()!.Value;
        numerics.M41.Should().Be(m[3]);
        numerics.M43.Should().Be(m[11]);
    }

    [Theory]
    [InlineData(SegmenterModel.SelfieMulticlass, "selfie_multiclass_256x256.tflite")]
    [InlineData(SegmenterModel.Hair, "hair_segmenter.tflite")]
    [InlineData(SegmenterModel.DeepLabV3, "deeplab_v3.tflite")]
    public void Image_segmenter_matches_mediapipe(SegmenterModel model, string goldenKey)
    {
        var expected = Golden.V2("image_segmenter").GetProperty(goldenKey);
        using var segmenter = ImageSegmenter.Create(new() { BaseOptions = Fixtures.Base, Model = model, OutputCategoryMask = true });
        using var image = Fixtures.Load(expected.GetProperty("image").GetString()!);
        var result = segmenter.Segment(image);

        var confidence = expected.GetProperty("confidence");
        result.ConfidenceMasks.Should().HaveCount(confidence.GetArrayLength());
        result.Labels.Should().HaveCount(confidence.GetArrayLength());
        result.ConfidenceMasks.Should().OnlyContain(m => m.Width == image.Width && m.Height == image.Height);
        var histogram = result.CategoryMask!.Histogram();
        var expectedHistogram = expected.GetProperty("category").GetProperty("histogram").EnumerateObject()
            .ToDictionary(b => int.Parse(b.Name), b => b.Value.GetSingle());
        if (model == SegmenterModel.DeepLabV3)
        {
            // cats_and_dogs.jpg sits on DeepLab's dog/horse decision boundary: the split between those two
            // classes flips with sub-pixel resampling differences, so compare background vs. foreground.
            histogram.GetValueOrDefault(0).Should().BeApproximately(expectedHistogram[0], 0.02f);
            result.ConfidenceMasks[0].Data.Average().Should().BeApproximately(confidence[0].GetProperty("mean").GetSingle(), 0.02f);
            return;
        }
        for (int c = 0; c < result.ConfidenceMasks.Count; c++)
            result.ConfidenceMasks[c].Data.Average().Should().BeApproximately(confidence[c].GetProperty("mean").GetSingle(), 0.015f, result.Labels[c]);
        foreach (var (category, fraction) in expectedHistogram)
            histogram.GetValueOrDefault(category).Should().BeApproximately(fraction, 0.015f, $"category {category}");
    }

    [Fact]
    public void Holistic_landmarker_matches_mediapipe()
    {
        using var landmarker = HolisticLandmarker.Create(new() { BaseOptions = Fixtures.Base });
        using var image = Fixtures.Load("pose.jpg");
        var result = landmarker.Detect(image);
        var expected = Golden.V2("holistic_landmarker").GetProperty("pose.jpg");
        result.Pose.Should().NotBeNull();
        Golden.MeanError(result.Pose!.Landmarks, Golden.Landmarks(expected.GetProperty("pose"))).Should().BeLessThan(0.006f);
        result.LeftHand.Should().NotBeNull();
        result.RightHand.Should().NotBeNull();
        Golden.MeanError(result.LeftHand!.Landmarks, Golden.Landmarks(expected.GetProperty("left_hand"))).Should().BeLessThan(0.01f);
        Golden.MeanError(result.RightHand!.Landmarks, Golden.Landmarks(expected.GetProperty("right_hand"))).Should().BeLessThan(0.01f);
        // Hand world landmarks are anchored at the pose's world wrists.
        result.LeftHand.WorldLandmarks[0].X.Should().BeApproximately(result.Pose.WorldLandmarks[(int)PoseLandmark.LeftWrist].X, 1e-5f);
        // MediaPipe finds no face here (the face is ~50 px, too small for its face detector); MediaPipe.NET
        // falls back to the pose's face landmarks, so it does.
        expected.GetProperty("face").GetArrayLength().Should().Be(0);
        result.Face.Should().NotBeNull();
    }

    [Fact]
    public void Image_embedder_matches_mediapipe()
    {
        var expected = Golden.V2("image_embedder");
        using var embedder = ImageEmbedder.Create(new() { BaseOptions = Fixtures.Base, L2Normalize = true });
        var e = new Dictionary<string, Embedding>();
        foreach (var name in new[] { "burger.jpg", "burger_crop.jpg", "cat.jpg" })
        {
            using var image = Fixtures.Load(name);
            e[name] = embedder.Embed(image).Embedding;
        }
        e["burger.jpg"].Dimension.Should().Be(expected.GetProperty("dim").GetInt32());
        ImageEmbedder.CosineSimilarity(e["burger.jpg"], e["burger_crop.jpg"])
            .Should().BeApproximately(expected.GetProperty("similarity_burger_burger_crop").GetDouble(), 0.03);
        ImageEmbedder.CosineSimilarity(e["burger.jpg"], e["cat.jpg"])
            .Should().BeApproximately(expected.GetProperty("similarity_burger_cat").GetDouble(), 0.05);
        // The same image embeds almost identically in MediaPipe and MediaPipe.NET.
        var first8 = expected.GetProperty("first8").GetProperty("cat.jpg").EnumerateArray().Select(v => v.GetSingle()).ToArray();
        for (int i = 0; i < 8; i++) e["cat.jpg"].Values[i].Should().BeApproximately(first8[i], 0.015f);
    }

    [Fact]
    public void Quantized_embeddings_keep_similarity()
    {
        using var embedder = ImageEmbedder.Create(new() { BaseOptions = Fixtures.Base, L2Normalize = true, Quantize = true });
        using var a = Fixtures.Load("burger.jpg");
        using var b = Fixtures.Load("burger_crop.jpg");
        var ea = embedder.Embed(a).Embedding;
        ea.Values.Should().BeEmpty();
        ea.QuantizedValues.Should().HaveCount(1024);
        Embedding.CosineSimilarity(ea, embedder.Embed(b).Embedding).Should().BeApproximately(0.92, 0.05);
    }

    [Fact]
    public void Interactive_segmenter_selects_the_object_under_the_point()
    {
        using var detector = ObjectDetector.Create(new() { BaseOptions = Fixtures.Base });
        using var segmenter = InteractiveSegmenter.Create(new() { BaseOptions = Fixtures.Base, OutputCategoryMask = true });
        using var image = Fixtures.Load("cats_and_dogs.jpg");
        foreach (var animal in detector.Detect(image).Detections.Take(2))
        {
            var box = animal.BoundingBox;
            var result = segmenter.Segment(image, RegionOfInterest.FromKeypoint(box.CenterX / image.Width, box.CenterY / image.Height));
            var mask = result.ConfidenceMask;
            float inside = 0, outside = 0;
            int nIn = 0, nOut = 0;
            for (int y = 0; y < image.Height; y += 4)
            {
                for (int x = 0; x < image.Width; x += 4)
                {
                    bool isInside = x >= box.X && x < box.Right && y >= box.Y && y < box.Bottom;
                    if (isInside) { inside += mask[x, y]; nIn++; } else { outside += mask[x, y]; nOut++; }
                }
            }
            (inside / nIn).Should().BeGreaterThan(0.4f, animal.TopCategory.CategoryName);
            (outside / nOut).Should().BeLessThan(0.1f, animal.TopCategory.CategoryName);
            result.CategoryMask!.Histogram().Should().ContainKey(0);
        }
    }

    [Fact]
    public void Svd_reconstructs_the_matrix()
    {
        double[] a = [3, 1, 2, -1, 4, 0.5, 2, 2, -3];
        FaceGeometry.Svd3(a, out var u, out var v);
        // A·V = U·Σ → the columns of A·V are orthogonal and match U up to scale.
        for (int c = 0; c < 3; c++)
        {
            double[] av = new double[3];
            for (int r = 0; r < 3; r++) av[r] = a[r * 3] * v[c] + a[r * 3 + 1] * v[3 + c] + a[r * 3 + 2] * v[6 + c];
            double s = Math.Sqrt(av.Sum(x => x * x));
            for (int r = 0; r < 3; r++) (av[r] / s).Should().BeApproximately(u[r * 3 + c], 1e-9);
        }
    }
}
